version: '3'

services:
  db:
    platform: linux/x86_64
    container_name: organizza-database
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root