version: '3'

services:
  db:
    platform: linux/x86_64
    container_name: organizza-database
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - organizza:/home/organizza
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  organizza:
